### ISSUE TITLE
终点签到失效

### ISSUE THREAD

**Issue by lazureice** [LovesAsuna/ForumSignin#12]
我本来以为只有我这里出错了。看了下你的 action 日志发现也是一样的。
> time="2022-06-12T23:12:14Z" level=info msg="exception \"Uncaught\" (0:0): ReferenceError: grecaptcha is not defined\n    at <anonymous>:1:1"

**Comment by LovesAsuna** [comment]
终点今天又双叒叕换验证方式了

**Comment by Dimlitter** [comment]
我也=-=

**Comment by LovesAsuna** [comment]
我看了一下你的action用的还是kt的版本

**Comment by Dimlitter** [comment]
是的，12号之后也无了
话说交给无头浏览器点击不应该不会变化太多么（最多变下路径？）

**Comment by LovesAsuna** [comment]
现在不是模拟点击了，这路子行不通了，是直接拿token

**Comment by Dimlitter** [comment]
你是去请求 https://bbs.zdfx.net/api/qiandao.html 了嘛
正常的签到页面不用过人机验证啊=-=

**Comment by LovesAsuna** [comment]
不是啊，我直接去拿token了，终点的操作现在全都用token了，但我现在是绕过这个人机验证，直接模拟验证后的获取token的操作

**Comment by Dimlitter** [comment]
哦哦 没仔细研究过==

**Comment by LovesAsuna** [comment]
终点天天改验证，很不安分，就不能学学花火吗

**Comment by yukimaware** [comment]
确实很烦人 摇一摇也失效了
