### ISSUE TITLE
终点论坛签到被检测

### ISSUE THREAD

**Issue by Dimlitter** [LovesAsuna/ForumSignin#3]
![Screenshot_2022-02-28-19-28-22-078_com.android.chrome.jpg](https://user-images.githubusercontent.com/68945228/155975981-7476a53e-2510-4770-9bce-91edd87ea5cc.jpg)

终点论坛的签到出现以上情况...

话说大佬是咋写的签到呀...我自己想爬个东西都爬不下来...action系统用的windows，语言也从没听过...太强啦

**Comment by LovesAsuna** [comment]
这个检测等我有空再看

**Comment by Dimlitter** [comment]
静候佳音

**Comment by Dimlitter** [comment]
别啊，虽然说模拟请求很困难，但是可以用selenium来解决
附上我搓的一个半成品脚本 https://t.me/viiberdaily/127
~（虽然我也要跑路了）~ 加油

**Comment by LovesAsuna** [comment]
我为了解决终点加captcha的问题，很早就用还是那个了selenium了，只不过这个编码问题我没有解决看着不舒服，而且seleniuim的api并不好用

**Comment by Dimlitter** [comment]
是这样，这selenium老是报connection aborted
~终点的网页编码不是utf-8么~
你现在的实现不是用的win吗，应该是可以的罢
就是这提示脚本签到，我自用的时候并不会有这种情况呀

**Comment by LovesAsuna** [comment]
是github action控制台看到的消息，我已经指定了gradle强制用utf-8了，但还是会出现部分汉族出现乱码的情况下，~~我还是第一次见到乱码能部分的~~

**Comment by Dimlitter** [comment]
等我有空尝试一下写一个action试试罢，放win服务器自动任务根本拉不起来，一直停留在webdriver的初始化界面，www

**Comment by LovesAsuna** [comment]
要不然我干脆用英文算了，反正没人在乎github action的运行日志？

**Comment by Dimlitter** [comment]
好呀，这倒无所谓，就是这被检测出脚本打卡...有办法解决么?
我对您所用的语言不太了解，所以看不太懂逻辑...

**Comment by LovesAsuna** [comment]
因为最开始是只有摇奖采用了验证，而签到没有采用，所以我只对摇奖采用了selenium，现在签到也是使用了验证了，而我还是用了以前的直接请求的方式，所以会被检测出是脚本打卡

**Comment by Dimlitter** [comment]
哦哦，您快更新，要么来抄抄我的py也行(

**Comment by Dimlitter** [comment]
还有您的sync job传入的参数写错了，哈哈哈

**Comment by LovesAsuna** [comment]
没懂这个sync job是哪里的

**Comment by Dimlitter** [comment]
`checkin.yml` 中的 `Sync with upstream`
报错如下：
```bash
Warning: Unexpected input(s) 'upstream_repository', 'upstream_branch', 'target_branch', 'git_pull_args', valid inputs are ['target_sync_branch', 'target_repo_token', 'upstream_repo_access_token', 'upstream_sync_repo', 'upstream_sync_branch', 'target_branch_checkout_args', 'git_log_format_args', 'upstream_pull_args', 'target_branch_push_args', 'git_config_user', 'git_config_email', 'git_config_pull_rebase', 'test_mode', 'host_domain']

**Comment by LovesAsuna** [comment]
xs，我是照抄的配置，然后更新了版本，然后新的版本跟旧版本参数不一样的

**Comment by Dimlitter** [comment]
当然是看fork的用户有报错啦

**Comment by LovesAsuna** [comment]
应该修好了

**Comment by Dimlitter** [comment]
好欸（狂喜）

**Comment by LovesAsuna** [comment]
#6
