### ISSUE TITLE
使用Go重写项目

### ISSUE THREAD

**Issue by LovesAsuna** [LovesAsuna/ForumSignin#7]

**Comment by Dimlitter** [comment]
支持！
> 刚入门go，前来围观

**Comment by LovesAsuna** [comment]
已经重写完了，在调试了

**Comment by Dimlitter** [comment]
有什么特别的features吗？
比如并发之类的?

**Comment by LovesAsuna** [comment]
速度会比kotlin版本的快很多，这是由浏览器模拟的框架决定的，但实际上两个都是用的协程。但既然用了action，效率高不高也没什么所谓了。我也只是学了go想拿来玩玩练习一下

**Comment by LovesAsuna** [comment]
@Dimlitter 救救，不会修了。github action的行为太诡异了

**Comment by Dimlitter** [comment]
下午考生化 嘤嘤嘤
等我考完回来康康(

**Comment by Dimlitter** [comment]
爆炸了，我自己本地的selenium都搞得晕头转向,这selenium获取的cookie拿到requests的session里发送就寄了

**Comment by LovesAsuna** [comment]
go这边用的不是selenium呀

**Comment by Dimlitter** [comment]
噢噢，我说的是我自己的repo来着
焦头烂额了都要（

**Comment by Dimlitter** [comment]
粗略的看了一遍，代码写的很清爽，可读性也很强，厉害呀

`context` `sync` `net`包的使用比我要熟练多了

花火论坛居然用的还是post呀

> 就是当中的各项签到，好像用了`go func` 和`chan`，但是又使用`sync.WaitGroup`控制了，感觉好像和线性执行没啥区别啊哈哈哈

**Comment by LovesAsuna** [comment]
:(不熟练，context我就花了半小时学了一下，其实用法就那几个。签到的话花火和终点是在不同的func，然后在终点又分别开了两个func来启动浏览器模拟摇奖和签到，效率上应该是会有提高的，我用test测过耗时的

**Comment by LovesAsuna** [comment]
现在问题就是。本地是基本没什么问题的，一旦跑在action上就会出现很多问题

**Comment by Dimlitter** [comment]
真的比我好多了，我还在摸爬滚打呢

勉强看得懂你在干啥哈哈哈

> 可能action环境不太一样? 你要不要换成windows其他系统试试?

**Comment by LovesAsuna** [comment]
我已经是把action跑在了action上了呀
> 你要不把workflow关了，明天手动用go分支跑action看看会不会出问题

**Comment by Dimlitter** [comment]
好 我明天试试

**Comment by LovesAsuna** [comment]
u1s1，go的这个chromedp好简洁啊，源码很容易读，还比selenium好用很多

**Comment by Dimlitter** [comment]
是啊 看起来真简洁

我已经快被selenium整晕了,它和requests的交互真是一言难尽啊

**Comment by Dimlitter** [comment]
看起来没什么问题呀

已经切`defualt branch`了,明天再来看看

**Comment by LovesAsuna** [comment]
确实看起来没啥问题，跑action就会卡住，比如终点签到的goroutine一直卡住不结束，摇奖的不打印日志，然后整个action就一直不会结束。然后看效果，虽然摇奖的没日志，它实际上又确实成功了，但签到该卡住还是卡住。
在本地跑终点的签到我这边也有点问题，整个运作流程不会卡住，但它是签到失败的，没有点击到，但是一debug之后它又会成功（可能运行时间变长了？），这一点比较匪夷所思

**Comment by Dimlitter** [comment]
emmm , 或许可以增加一个对页面元素是否出现的判断 (像是`selenium`的`WebDriverWait`) ? 听你的描述,像是页面未加载完成就点击造成的?

我看到你对签到的时限做了限制,但是中间没有延时或者之类的操作.有没有可能是在`headless` ( 无界面输出 ? )情况下`chromedp`跑的太快了?

> 实在不行还有一个笨办法嘛 , cron多运行几次咯~

**Comment by LovesAsuna** [comment]
从chromedp的源码上看，点击元素会默认附加一个判断元素是否可见的条件的

**Comment by Dimlitter** [comment]
啊 刚刚点进去看了下确实是这样. 

那就奇怪了

**Comment by LovesAsuna** [comment]
![image](https://user-images.githubusercontent.com/32810896/166390503-e4676ba4-a589-41dc-8c07-052c6123bc72.png)

**Comment by LovesAsuna** [comment]
我刚刚尝试了一下打开图形界面，删掉cancel，然后就成功了，我猜测可能是点击请求并不会等待他的响应就直接结束掉了，然后它慢一点关掉也许就可以了

**Comment by Dimlitter** [comment]
我在尝试用`context.WithTimeout`来代替`for循环`控制时间，这可能写的稍微优雅点？

但是刚刚测试好像签到失败了。。果然是我不太会用嘛www

**Comment by LovesAsuna** [comment]
我一开始用的就是WithTimeOut，然后我就发现action的机子跟我的机子性能差距太大了，这个超时时间不好顶，所以我才改成了失败的尝试次数

**Comment by Dimlitter** [comment]
action的机子好像配置挺高的吧，有2C7G来着

所以您的机子不会是4C8G的巨无霸罢（

**Comment by LovesAsuna** [comment]
是8C32G(小声

**Comment by Dimlitter** [comment]
我超超超

什么大户人家www

**Comment by LovesAsuna** [comment]
初步定位到卡死问题出现在获取摇奖结果上

**Comment by LovesAsuna** [comment]
发现可以另辟蹊径，直接用浏览器拿到token，再按照老办法发post请求，这样子后续步骤就不需要用浏览器模拟了，处理起来更方柏

**Comment by Dimlitter** [comment]
好想法！

这样就不用管玄学的浏览器行为啦

**Comment by LovesAsuna** [comment]
已经把摇奖部分实现了，明天把签到写了。一天只能测试一次太麻烦了

**Comment by Dimlitter** [comment]
现在终点开放注册了罢，可以多注册几个?
