### ISSUE TITLE
cookie 应该填在哪？

### ISSUE THREAD

**Issue by lazureice** [LovesAsuna/ForumSignin#9]
需要终点的签到，但是一般的签到框架会被检测为脚本签到，然后搜到了这个项目。

不敢用github actions，怕被封号。
cookie 填在 `.github/workflows/checkin.yml` 里没用，似乎只对 github action 有效？
`gradle.properties` 也不行，`ZDFX_COOKIE=` 和 `Secrets.ZDFX_COOKIE=` 都不对。依然提示：
> Zdfx‘s cookie has not set

**Comment by LovesAsuna** [comment]
COOKIE是填在项目的secret里，README应该写的很清楚了啊

**Comment by lazureice** [comment]
> Settings -> Secruity -> Secrets -> Actions

看起来还是github action。
我没用action。
刚刚看了下代码，原来用的是系统的环境变量，而不是项目的……

然后运行了发现driver出错：
https://github.com/LovesAsuna/ForumSignin/blob/3ca402061c2da4455a49b09bad450111620af4bb/src/main/kotlin/com/hyosakura/signin/sign/forum/discuz/Discuz.kt#L23
但我是在linux上跑的。

不过这个issue已经解决了，closed.
